-- Europa CRM linked workflow upgrade. Additive migration: existing display-name fields are retained for compatibility.
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "ownerId" TEXT, ADD COLUMN IF NOT EXISTS "convertedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "convertedById" TEXT, ADD COLUMN IF NOT EXISTS "convertedContactId" TEXT, ADD COLUMN IF NOT EXISTS "convertedAccountId" TEXT, ADD COLUMN IF NOT EXISTS "convertedOpportunityId" TEXT;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "ownerId" TEXT, ADD COLUMN IF NOT EXISTS "accountId" TEXT, ADD COLUMN IF NOT EXISTS "sourceLeadId" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "normalizedName" TEXT, ADD COLUMN IF NOT EXISTS "lifecycleStatus" TEXT NOT NULL DEFAULT 'Prospect', ADD COLUMN IF NOT EXISTS "primaryContactId" TEXT, ADD COLUMN IF NOT EXISTS "ownerId" TEXT;
ALTER TABLE "Opportunity" ADD COLUMN IF NOT EXISTS "accountId" TEXT, ADD COLUMN IF NOT EXISTS "primaryContactId" TEXT, ADD COLUMN IF NOT EXISTS "sourceLeadId" TEXT, ADD COLUMN IF NOT EXISTS "finalAmount" INTEGER, ADD COLUMN IF NOT EXISTS "closeNotes" TEXT, ADD COLUMN IF NOT EXISTS "deliveryType" TEXT, ADD COLUMN IF NOT EXISTS "ownerId" TEXT;
ALTER TABLE "Activity" ADD COLUMN IF NOT EXISTS "relatedEntityType" TEXT, ADD COLUMN IF NOT EXISTS "relatedEntityId" TEXT, ADD COLUMN IF NOT EXISTS "ownerId" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "vacancyCount" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Interview" ADD COLUMN IF NOT EXISTS "applicationId" TEXT, ADD COLUMN IF NOT EXISTS "candidateId" TEXT, ADD COLUMN IF NOT EXISTS "jobId" TEXT;
ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "applicationId" TEXT, ADD COLUMN IF NOT EXISTS "interviewId" TEXT, ADD COLUMN IF NOT EXISTS "candidateId" TEXT, ADD COLUMN IF NOT EXISTS "jobId" TEXT, ADD COLUMN IF NOT EXISTS "revision" INTEGER NOT NULL DEFAULT 1, ADD COLUMN IF NOT EXISTS "decisionReason" TEXT;
ALTER TABLE "Bench" ADD COLUMN IF NOT EXISTS "candidateId" TEXT, ADD COLUMN IF NOT EXISTS "ownerId" TEXT;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "benchConsultantId" TEXT, ADD COLUMN IF NOT EXISTS "requirementId" TEXT, ADD COLUMN IF NOT EXISTS "matchPercentage" INTEGER, ADD COLUMN IF NOT EXISTS "matchDetails" JSONB;
ALTER TABLE "Placement" ADD COLUMN IF NOT EXISTS "submissionId" TEXT, ADD COLUMN IF NOT EXISTS "benchConsultantId" TEXT;
ALTER TABLE "AiProject" ADD COLUMN IF NOT EXISTS "progress" INTEGER NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS "ownerId" TEXT, ADD COLUMN IF NOT EXISTS "sourceOpportunityId" TEXT, ADD COLUMN IF NOT EXISTS "accountId" TEXT, ADD COLUMN IF NOT EXISTS "contactId" TEXT;
ALTER TABLE "AiTask" ADD COLUMN IF NOT EXISTS "projectId" TEXT, ADD COLUMN IF NOT EXISTS "assigneeId" TEXT, ADD COLUMN IF NOT EXISTS "weight" INTEGER NOT NULL DEFAULT 1, ADD COLUMN IF NOT EXISTS "mandatory" BOOLEAN NOT NULL DEFAULT true, ADD COLUMN IF NOT EXISTS "blockedReason" TEXT;
ALTER TABLE "AiResource" ADD COLUMN IF NOT EXISTS "capacityPercent" INTEGER NOT NULL DEFAULT 100;

CREATE TABLE IF NOT EXISTS "CandidateApplication" ("id" TEXT PRIMARY KEY, "candidateId" TEXT NOT NULL, "jobId" TEXT NOT NULL, "stage" TEXT NOT NULL DEFAULT 'New', "ownerId" TEXT, "rejectionReason" TEXT, "placedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "CandidateApplication_candidateId_jobId_key" ON "CandidateApplication"("candidateId","jobId");
CREATE TABLE IF NOT EXISTS "ApplicationStatusHistory" ("id" TEXT PRIMARY KEY, "applicationId" TEXT NOT NULL, "fromStatus" TEXT, "toStatus" TEXT NOT NULL, "reason" TEXT, "changedById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "OpportunityStageHistory" ("id" TEXT PRIMARY KEY, "opportunityId" TEXT NOT NULL, "fromStage" TEXT, "toStage" TEXT NOT NULL, "reason" TEXT, "changedById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "OfferRevision" ("id" TEXT PRIMARY KEY, "offerId" TEXT NOT NULL, "revision" INTEGER NOT NULL, "amount" INTEGER NOT NULL, "joiningDate" TEXT, "notes" TEXT, "createdById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX IF NOT EXISTS "OfferRevision_offerId_revision_key" ON "OfferRevision"("offerId","revision");
CREATE TABLE IF NOT EXISTS "Requirement" ("id" TEXT PRIMARY KEY, "title" TEXT NOT NULL, "clientCompany" TEXT NOT NULL, "vendorCompany" TEXT, "skills" TEXT NOT NULL, "minExperience" INTEGER NOT NULL DEFAULT 0, "location" TEXT, "visaRequirements" TEXT, "maxRate" INTEGER, "status" TEXT NOT NULL DEFAULT 'Open', "customData" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "CampaignMember" ("id" TEXT PRIMARY KEY, "campaignId" TEXT NOT NULL, "contactId" TEXT, "email" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'Pending', "unsubscribedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "CampaignMember_campaignId_email_key" ON "CampaignMember"("campaignId","email");
CREATE TABLE IF NOT EXISTS "EmailEvent" ("id" TEXT PRIMARY KEY, "campaignMemberId" TEXT NOT NULL, "eventType" TEXT NOT NULL, "providerMessageId" TEXT, "metadata" JSONB, "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "ProjectTaskTemplate" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL UNIQUE, "description" TEXT, "defaultWeight" INTEGER NOT NULL DEFAULT 1, "mandatory" BOOLEAN NOT NULL DEFAULT true, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "ProjectResource" ("id" TEXT PRIMARY KEY, "projectId" TEXT NOT NULL, "resourceId" TEXT NOT NULL, "allocationPercent" INTEGER NOT NULL DEFAULT 100, "startDate" TEXT, "endDate" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "ProjectResource_projectId_resourceId_key" ON "ProjectResource"("projectId","resourceId");
CREATE TABLE IF NOT EXISTS "Notification" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL, "type" TEXT NOT NULL, "title" TEXT NOT NULL, "message" TEXT NOT NULL, "entityType" TEXT, "entityId" TEXT, "readAt" TIMESTAMP(3), "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "AuditLog" ("id" TEXT PRIMARY KEY, "userId" TEXT, "action" TEXT NOT NULL, "entityType" TEXT NOT NULL, "entityId" TEXT, "beforeData" JSONB, "afterData" JSONB, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE UNIQUE INDEX IF NOT EXISTS "Lead_convertedContactId_key" ON "Lead"("convertedContactId");
CREATE UNIQUE INDEX IF NOT EXISTS "Lead_convertedOpportunityId_key" ON "Lead"("convertedOpportunityId");
CREATE UNIQUE INDEX IF NOT EXISTS "Bench_candidateId_key" ON "Bench"("candidateId");
CREATE UNIQUE INDEX IF NOT EXISTS "Placement_submissionId_key" ON "Placement"("submissionId");
CREATE UNIQUE INDEX IF NOT EXISTS "AiProject_sourceOpportunityId_key" ON "AiProject"("sourceOpportunityId");

-- Foreign keys are added only after nullable columns exist, preserving current data.
ALTER TABLE "CandidateApplication" ADD CONSTRAINT "CandidateApplication_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate"("id") ON DELETE CASCADE;
ALTER TABLE "CandidateApplication" ADD CONSTRAINT "CandidateApplication_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE RESTRICT;
ALTER TABLE "ApplicationStatusHistory" ADD CONSTRAINT "ApplicationStatusHistory_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "CandidateApplication"("id") ON DELETE CASCADE;
ALTER TABLE "OpportunityStageHistory" ADD CONSTRAINT "OpportunityStageHistory_opportunityId_fkey" FOREIGN KEY ("opportunityId") REFERENCES "Opportunity"("id") ON DELETE CASCADE;
ALTER TABLE "OfferRevision" ADD CONSTRAINT "OfferRevision_offerId_fkey" FOREIGN KEY ("offerId") REFERENCES "Offer"("id") ON DELETE CASCADE;
ALTER TABLE "CampaignMember" ADD CONSTRAINT "CampaignMember_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "Campaign"("id") ON DELETE CASCADE;
ALTER TABLE "EmailEvent" ADD CONSTRAINT "EmailEvent_campaignMemberId_fkey" FOREIGN KEY ("campaignMemberId") REFERENCES "CampaignMember"("id") ON DELETE CASCADE;
ALTER TABLE "ProjectResource" ADD CONSTRAINT "ProjectResource_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "AiProject"("id") ON DELETE CASCADE;
ALTER TABLE "ProjectResource" ADD CONSTRAINT "ProjectResource_resourceId_fkey" FOREIGN KEY ("resourceId") REFERENCES "AiResource"("id") ON DELETE RESTRICT;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;

ALTER TABLE "Lead" ADD CONSTRAINT "Lead_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_convertedContactId_fkey" FOREIGN KEY ("convertedContactId") REFERENCES "Contact"("id") ON DELETE SET NULL;
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_convertedAccountId_fkey" FOREIGN KEY ("convertedAccountId") REFERENCES "Account"("id") ON DELETE SET NULL;
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_convertedOpportunityId_fkey" FOREIGN KEY ("convertedOpportunityId") REFERENCES "Opportunity"("id") ON DELETE SET NULL;
ALTER TABLE "Contact" ADD CONSTRAINT "Contact_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "Contact" ADD CONSTRAINT "Contact_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE SET NULL;
ALTER TABLE "Contact" ADD CONSTRAINT "Contact_sourceLeadId_fkey" FOREIGN KEY ("sourceLeadId") REFERENCES "Lead"("id") ON DELETE SET NULL;
ALTER TABLE "Account" ADD CONSTRAINT "Account_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "Account" ADD CONSTRAINT "Account_primaryContactId_fkey" FOREIGN KEY ("primaryContactId") REFERENCES "Contact"("id") ON DELETE SET NULL;
ALTER TABLE "Opportunity" ADD CONSTRAINT "Opportunity_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE RESTRICT;
ALTER TABLE "Opportunity" ADD CONSTRAINT "Opportunity_primaryContactId_fkey" FOREIGN KEY ("primaryContactId") REFERENCES "Contact"("id") ON DELETE SET NULL;
ALTER TABLE "Opportunity" ADD CONSTRAINT "Opportunity_sourceLeadId_fkey" FOREIGN KEY ("sourceLeadId") REFERENCES "Lead"("id") ON DELETE SET NULL;
ALTER TABLE "Opportunity" ADD CONSTRAINT "Opportunity_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "Activity" ADD CONSTRAINT "Activity_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "CandidateApplication" ADD CONSTRAINT "CandidateApplication_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "Interview" ADD CONSTRAINT "Interview_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "CandidateApplication"("id") ON DELETE CASCADE;
ALTER TABLE "Interview" ADD CONSTRAINT "Interview_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate"("id") ON DELETE SET NULL;
ALTER TABLE "Interview" ADD CONSTRAINT "Interview_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE SET NULL;
ALTER TABLE "Offer" ADD CONSTRAINT "Offer_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "CandidateApplication"("id") ON DELETE CASCADE;
ALTER TABLE "Offer" ADD CONSTRAINT "Offer_interviewId_fkey" FOREIGN KEY ("interviewId") REFERENCES "Interview"("id") ON DELETE SET NULL;
ALTER TABLE "Offer" ADD CONSTRAINT "Offer_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate"("id") ON DELETE SET NULL;
ALTER TABLE "Offer" ADD CONSTRAINT "Offer_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE SET NULL;
ALTER TABLE "Bench" ADD CONSTRAINT "Bench_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate"("id") ON DELETE SET NULL;
ALTER TABLE "Bench" ADD CONSTRAINT "Bench_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "Submission" ADD CONSTRAINT "Submission_benchConsultantId_fkey" FOREIGN KEY ("benchConsultantId") REFERENCES "Bench"("id") ON DELETE RESTRICT;
ALTER TABLE "Submission" ADD CONSTRAINT "Submission_requirementId_fkey" FOREIGN KEY ("requirementId") REFERENCES "Requirement"("id") ON DELETE SET NULL;
ALTER TABLE "Placement" ADD CONSTRAINT "Placement_submissionId_fkey" FOREIGN KEY ("submissionId") REFERENCES "Submission"("id") ON DELETE SET NULL;
ALTER TABLE "Placement" ADD CONSTRAINT "Placement_benchConsultantId_fkey" FOREIGN KEY ("benchConsultantId") REFERENCES "Bench"("id") ON DELETE RESTRICT;
ALTER TABLE "AiProject" ADD CONSTRAINT "AiProject_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "AiProject" ADD CONSTRAINT "AiProject_sourceOpportunityId_fkey" FOREIGN KEY ("sourceOpportunityId") REFERENCES "Opportunity"("id") ON DELETE SET NULL;
ALTER TABLE "AiProject" ADD CONSTRAINT "AiProject_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE RESTRICT;
ALTER TABLE "AiProject" ADD CONSTRAINT "AiProject_contactId_fkey" FOREIGN KEY ("contactId") REFERENCES "Contact"("id") ON DELETE SET NULL;
ALTER TABLE "AiTask" ADD CONSTRAINT "AiTask_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "AiProject"("id") ON DELETE CASCADE;
ALTER TABLE "AiTask" ADD CONSTRAINT "AiTask_assigneeId_fkey" FOREIGN KEY ("assigneeId") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL;
