ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "customData" JSONB;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "customData" JSONB;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "customData" JSONB;
ALTER TABLE "Opportunity" ADD COLUMN IF NOT EXISTS "customData" JSONB;
ALTER TABLE "Campaign" ADD COLUMN IF NOT EXISTS "customData" JSONB;
ALTER TABLE "Activity" ADD COLUMN IF NOT EXISTS "customData" JSONB;
ALTER TABLE "Candidate" ADD COLUMN IF NOT EXISTS "customData" JSONB;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "customData" JSONB;
ALTER TABLE "Interview" ADD COLUMN IF NOT EXISTS "customData" JSONB;
ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "customData" JSONB;
ALTER TABLE "Bench" ADD COLUMN IF NOT EXISTS "customData" JSONB;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "customData" JSONB;
ALTER TABLE "Placement" ADD COLUMN IF NOT EXISTS "customData" JSONB;
ALTER TABLE "AiProject" ADD COLUMN IF NOT EXISTS "customData" JSONB;
ALTER TABLE "AiTask" ADD COLUMN IF NOT EXISTS "customData" JSONB;
ALTER TABLE "AiResource" ADD COLUMN IF NOT EXISTS "customData" JSONB;
CREATE TABLE IF NOT EXISTS "AppSetting" (
  "id" TEXT NOT NULL,
  "key" TEXT NOT NULL,
  "value" JSONB NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "AppSetting_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "AppSetting_key_key" ON "AppSetting"("key");
