import { useEffect, useMemo, useState } from 'react';
import { Copy, Mail, Pencil, Plus, Search, Send, Server, Trash2, Users } from 'lucide-react';
import { toast } from 'sonner';
import { api } from '@/lib/api';
import { useApp } from '@/context/AppContext';

type MailModule='sales'|'it'|'bench'|'ai';
type Ref={entityType:string;entityId:string};
type Recipient=Ref&{name:string;email:string};
type Group={id:string;groupName:string;description?:string|null;module:MailModule;members?:Ref[];recipients?:Recipient[];_count?:{members:number}};
const details:Record<MailModule,{title:string;description:string;entities:{value:string;label:string}[];prefix:string}>={
 sales:{title:'S-mail',description:'Sales and marketing email workspace.',prefix:'sales-mail',entities:[{value:'lead',label:'Leads'},{value:'contact',label:'Contacts'},{value:'account',label:'Accounts'}]},
 it:{title:'IT-mail',description:'IT recruitment email workspace.',prefix:'recruitment-mail',entities:[{value:'candidate',label:'Candidates'}]},
 bench:{title:'Bench-mail',description:'Bench consultant email workspace.',prefix:'bench-mail',entities:[{value:'candidate',label:'Consultants'}]},
 ai:{title:'AI-mail',description:'AI Team email workspace.',prefix:'ai-mail',entities:[{value:'contact',label:'Contacts'},{value:'account',label:'Accounts'},{value:'user',label:'Team Users'}]},
};

export function MailPage({module}:{module:MailModule}){
 const meta=useMemo(()=>details[module],[module]); const {hasPermission}=useApp();
 const [tab,setTab]=useState<'compose'|'groups'>('compose'); const [groups,setGroups]=useState<Group[]>([]); const [search,setSearch]=useState('');
 const [selectedGroup,setSelectedGroup]=useState(''); const [recipients,setRecipients]=useState<Recipient[]>([]); const [to,setTo]=useState(''); const [subject,setSubject]=useState(''); const [body,setBody]=useState(''); const [busy,setBusy]=useState(false); const [status,setStatus]=useState('Not checked');
 const [editing,setEditing]=useState<Group|null>(null); const [groupName,setGroupName]=useState(''); const [description,setDescription]=useState(''); const [entityType,setEntityType]=useState(meta.entities[0].value); const [memberSearch,setMemberSearch]=useState(''); const [results,setResults]=useState<Recipient[]>([]); const [members,setMembers]=useState<Recipient[]>([]);
 const can=(a:string)=>hasPermission(`${meta.prefix}-${a}`);
 const loadGroups=async()=>{if(!can('groups-view'))return;try{setGroups((await api.listMailGroups<Group>(module,search)).data);}catch(e){toast.error(e instanceof Error?e.message:'Unable to load groups');}};
 useEffect(()=>{void loadGroups();},[module,search]); useEffect(()=>{setEntityType(meta.entities[0].value);},[module]);
 const selectGroup=async(id:string)=>{setSelectedGroup(id);if(!id){setRecipients([]);return;}try{const g=await api.getMailGroup<Group>(id);setRecipients(g.recipients??[]);}catch(e){toast.error(e instanceof Error?e.message:'Unable to load group');}};
 const lookup=async()=>{try{setResults((await api.searchMailRecipients<Recipient>(module,entityType,memberSearch)).data.filter(x=>!members.some(m=>m.entityType===x.entityType&&m.entityId===x.entityId)));}catch(e){toast.error(e instanceof Error?e.message:'Unable to search contacts');}};
 const openNew=()=>{setEditing({id:'',groupName:'',module});setGroupName('');setDescription('');setMembers([]);setResults([]);};
 const openEdit=async(g:Group)=>{try{const full=await api.getMailGroup<Group>(g.id);setEditing(full);setGroupName(full.groupName);setDescription(full.description??'');setMembers(full.recipients??[]);}catch(e){toast.error(e instanceof Error?e.message:'Unable to open group');}};
 const saveGroup=async()=>{if(!groupName.trim())return toast.error('Enter a group name');setBusy(true);try{const payload={module,groupName:groupName.trim(),description,members:members.map(({entityType,entityId})=>({entityType,entityId}))};if(editing?.id)await api.updateMailGroup(editing.id,payload);else await api.createMailGroup(payload);toast.success(editing?.id?'Group updated':'Group created');setEditing(null);await loadGroups();}catch(e){toast.error(e instanceof Error?e.message:'Unable to save group');}finally{setBusy(false);}};
 const removeGroup=async(g:Group)=>{if(!confirm(`Delete ${g.groupName}?`))return;try{await api.deleteMailGroup(g.id);toast.success('Group deleted');await loadGroups();}catch(e){toast.error(e instanceof Error?e.message:'Unable to delete group');}};
 const duplicate=async(g:Group)=>{try{await api.duplicateMailGroup(g.id);toast.success('Group duplicated');await loadGroups();}catch(e){toast.error(e instanceof Error?e.message:'Unable to duplicate group');}};
 const send=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await api.sendEmail({module,to:to||undefined,subject,body,members:recipients.map(({entityType,entityId})=>({entityType,entityId}))});toast.success('Email sent');setTo('');setSubject('');setBody('');setSelectedGroup('');setRecipients([]);}catch(e){toast.error(e instanceof Error?e.message:'Unable to send');}finally{setBusy(false);}};
 return <div className="px-5 py-5">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-sm font-bold text-[#009E92]">Email</div><h1 className="mt-1 text-2xl font-extrabold text-slate-950">{meta.title}</h1></div><button type="button" onClick={async()=>{try{const r=await api.checkEmail(module);setStatus(r.sender?`Connected as ${r.sender}`:'SMTP verified');toast.success('SMTP connection ready');}catch(e){const msg=e instanceof Error?e.message:'Failed';setStatus(msg);toast.error(msg);}}} className="crm-secondary-button"><Server className="h-4 w-4"/>Check SMTP</button></div>
  <div className="mt-5 flex gap-2 border-b border-[#E4ECF3]"><button onClick={()=>setTab('compose')} className={`px-4 py-3 font-bold ${tab==='compose'?'border-b-2 border-[#009E92] text-[#009E92]':'text-slate-600'}`}>Compose</button>{can('groups-view')&&<button onClick={()=>setTab('groups')} className={`px-4 py-3 font-bold ${tab==='groups'?'border-b-2 border-[#009E92] text-[#009E92]':'text-slate-600'}`}>Mail Groups</button>}</div>
  {tab==='compose'?<div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]"><form onSubmit={send} className="crm-card p-5"><div className="flex items-center gap-2 border-b border-[#E4ECF3] pb-4"><Mail className="h-5 w-5 text-[#009E92]"/><h2 className="text-lg font-extrabold">Compose email</h2></div><div className="mt-4 space-y-4">
   {can('groups-view')&&<label className="block"><span className="mb-1.5 block text-sm font-bold">Select Mail Group</span><select className="crm-input" value={selectedGroup} onChange={e=>void selectGroup(e.target.value)}><option value="">No saved group</option>{groups.map(g=><option key={g.id} value={g.id}>{g.groupName} ({g._count?.members??0})</option>)}</select></label>}
   {recipients.length>0&&<div><div className="mb-2 text-sm font-bold">Recipients from group</div><div className="flex flex-wrap gap-2">{recipients.map(r=><button type="button" key={`${r.entityType}:${r.entityId}`} onClick={()=>setRecipients(x=>x.filter(y=>y!==r))} className="rounded-full bg-slate-100 px-3 py-1.5 text-sm font-semibold text-slate-700">{r.name} ×</button>)}</div><p className="mt-1 text-xs text-slate-500">Removing recipients here does not modify the saved group.</p></div>}
   <label className="block"><span className="mb-1.5 block text-sm font-bold">Additional email</span><input type="email" className="crm-input" value={to} onChange={e=>setTo(e.target.value)} placeholder="optional@example.com"/></label><label className="block"><span className="mb-1.5 block text-sm font-bold">Subject</span><input required className="crm-input" value={subject} onChange={e=>setSubject(e.target.value)}/></label><label className="block"><span className="mb-1.5 block text-sm font-bold">Message</span><textarea required className="min-h-56 w-full rounded-lg border-2 border-[#E4ECF3] p-3" value={body} onChange={e=>setBody(e.target.value)}/></label>{can('compose')&&<button disabled={busy} className="crm-primary-button"><Send className="h-4 w-4"/>{busy?'Sending…':'Send email'}</button>}</div></form><aside className="crm-card h-fit p-5"><h2 className="font-extrabold">Connection status</h2><p className="mt-3 break-words text-sm text-slate-600">{status}</p></aside></div>:
  <div className="mt-5 crm-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input className="crm-input pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search personal groups"/></div>{can('groups-create')&&<button onClick={openNew} className="crm-primary-button"><Plus className="h-4 w-4"/>Create Group</button>}</div><div className="mt-4 space-y-3">{groups.map(g=><div key={g.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#E4ECF3] p-4"><div><h3 className="font-extrabold text-slate-900">{g.groupName}</h3><p className="text-sm text-slate-500">{g.description||'No description'} · {g._count?.members??0} members</p></div><div className="flex gap-2"><button className="crm-secondary-button" onClick={()=>void openEdit(g)}><Users className="h-4 w-4"/>View</button>{can('groups-edit')&&<button className="crm-secondary-button" onClick={()=>void openEdit(g)}><Pencil className="h-4 w-4"/>Edit</button>}{can('groups-create')&&<button className="crm-secondary-button" onClick={()=>void duplicate(g)}><Copy className="h-4 w-4"/>Duplicate</button>}{can('groups-delete')&&<button className="crm-secondary-button" onClick={()=>void removeGroup(g)}><Trash2 className="h-4 w-4"/>Delete</button>}</div></div>)}{!groups.length&&<div className="py-10 text-center text-slate-500">No personal mail groups yet.</div>}</div></div>}
  {editing&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-2xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><h2 className="text-xl font-extrabold">{editing.id?'Edit Mail Group':'Create Mail Group'}</h2><button onClick={()=>setEditing(null)}>×</button></div><div className="mt-4 grid gap-4 md:grid-cols-2"><label><span className="mb-1 block text-sm font-bold">Group name</span><input className="crm-input" value={groupName} onChange={e=>setGroupName(e.target.value)}/></label><label><span className="mb-1 block text-sm font-bold">Description</span><input className="crm-input" value={description} onChange={e=>setDescription(e.target.value)}/></label></div><div className="mt-5 grid gap-3 md:grid-cols-[180px_1fr_auto]"><select className="crm-input" value={entityType} onChange={e=>setEntityType(e.target.value)}>{meta.entities.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select><input className="crm-input" value={memberSearch} onChange={e=>setMemberSearch(e.target.value)} placeholder="Search CRM contacts"/><button onClick={()=>void lookup()} className="crm-secondary-button"><Search className="h-4 w-4"/>Search</button></div><div className="mt-4 grid gap-4 md:grid-cols-2"><div><h3 className="font-bold">Search results</h3><div className="mt-2 max-h-64 space-y-2 overflow-auto">{results.map(r=><button key={`${r.entityType}:${r.entityId}`} onClick={()=>{setMembers(m=>[...m,r]);setResults(x=>x.filter(y=>y!==r));}} className="w-full rounded-lg border p-3 text-left"><b>{r.name}</b><div className="text-xs text-slate-500">{r.email}</div></button>)}</div></div><div><h3 className="font-bold">Members ({members.length})</h3><div className="mt-2 max-h-64 space-y-2 overflow-auto">{members.map(r=><button key={`${r.entityType}:${r.entityId}`} onClick={()=>setMembers(x=>x.filter(y=>y!==r))} className="w-full rounded-lg bg-slate-100 p-3 text-left"><b>{r.name}</b><div className="text-xs text-slate-500">{r.email} · click to remove</div></button>)}</div></div></div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setEditing(null)} className="crm-secondary-button">Cancel</button><button disabled={busy} onClick={()=>void saveGroup()} className="crm-primary-button">Save Group</button></div></div></div>}
 </div>;
}
