import 'dotenv/config';
import { z } from 'zod';

const schema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  PORT: z.coerce.number().default(4000),
  FRONTEND_URL: z.string().default('http://localhost:5173'),
  CORS_ORIGIN: z.string().optional(),
  JWT_SECRET: z.string().min(32),
  DATABASE_URL: z.string().min(1),
  AWS_REGION: z.string().default('ap-south-1'),
  AWS_ACCESS_KEY_ID: z.string().optional(),
  AWS_SECRET_ACCESS_KEY: z.string().optional(),
  AWS_S3_BUCKET: z.string().optional(),
  SMTP_HOST: z.string().optional(),
  SMTP_PORT: z.coerce.number().default(587),
  SMTP_USER: z.string().optional(),
  SMTP_PASS: z.string().optional(),
  SMTP_FROM: z.string().default('Europa CRM <crm@example.com>'),
  SALES_SMTP_HOST: z.string().optional(),
  SALES_SMTP_PORT: z.coerce.number().optional(),
  SALES_SMTP_USER: z.string().optional(),
  SALES_SMTP_PASS: z.string().optional(),
  SALES_SMTP_FROM: z.string().optional(),
  RECRUITER_SMTP_HOST: z.string().optional(),
  RECRUITER_SMTP_PORT: z.coerce.number().optional(),
  RECRUITER_SMTP_USER: z.string().optional(),
  RECRUITER_SMTP_PASS: z.string().optional(),
  RECRUITER_SMTP_FROM: z.string().optional(),
  BENCHSALES_SMTP_HOST: z.string().optional(),
  BENCHSALES_SMTP_PORT: z.coerce.number().optional(),
  BENCHSALES_SMTP_USER: z.string().optional(),
  BENCHSALES_SMTP_PASS: z.string().optional(),
  BENCHSALES_SMTP_FROM: z.string().optional(),
  AITEAM_SMTP_HOST: z.string().optional(),
  AITEAM_SMTP_PORT: z.coerce.number().optional(),
  AITEAM_SMTP_USER: z.string().optional(),
  AITEAM_SMTP_PASS: z.string().optional(),
  AITEAM_SMTP_FROM: z.string().optional(),
  GOOGLE_CLIENT_ID: z.string().optional(),
  GOOGLE_CLIENT_SECRET: z.string().optional(),
  GOOGLE_OAUTH_REDIRECT_URI: z.string().default('http://localhost:4000/api/email-accounts/oauth/callback'),
  GOOGLE_TOKEN_ENCRYPTION_KEY: z.string().optional(),
  ADMIN_NAME: z.string().default('Europa Administrator'),
  ADMIN_USERNAME: z.string().default('admin'),
  ADMIN_EMAIL: z.string().email().default('admin@europacrm.local'),
  ADMIN_PASSWORD: z.string().min(8).default('admin123'),
});

export const env = schema.parse(process.env);
